import {MigrationInterface, QueryRunner} from "typeorm";

export class Migration1621667603333 implements MigrationInterface {
    name = 'Migration1621667603333'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "timetable" DROP CONSTRAINT "FK_531f53d06003b9e25ed9f2f0cd3"`);
        await queryRunner.query(`ALTER TABLE "term" DROP CONSTRAINT "PK_55b0479f0743f2e5d5ec414821e"`);
        await queryRunner.query(`ALTER TABLE "term" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "term" ADD "id" uuid NOT NULL DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "term" ADD CONSTRAINT "PK_55b0479f0743f2e5d5ec414821e" PRIMARY KEY ("id")`);
        await queryRunner.query(`COMMENT ON COLUMN "term"."weekNames" IS NULL`);
        await queryRunner.query(`ALTER TABLE "term" ALTER COLUMN "weekNames" SET DEFAULT array[]::varchar[]`);
        await queryRunner.query(`ALTER TABLE "session_allocation" DROP CONSTRAINT "FK_4229fc0a3545c3afd0bfb0bb7e4"`);
        await queryRunner.query(`ALTER TABLE "session_allocation" DROP CONSTRAINT "FK_4ad45c42f963d66b7d38b6e9fe8"`);
        await queryRunner.query(`ALTER TABLE "session_allocation" DROP CONSTRAINT "UQ_48fa99dd8231087c41a285f606f"`);
        await queryRunner.query(`ALTER TABLE "session_allocation" DROP CONSTRAINT "PK_52c1e1b8d5dfae4448fb5c0d122"`);
        await queryRunner.query(`ALTER TABLE "session_allocation" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "session_allocation" ADD "id" uuid NOT NULL DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "session_allocation" ADD CONSTRAINT "PK_52c1e1b8d5dfae4448fb5c0d122" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "session_allocation" DROP COLUMN "sessionId"`);
        await queryRunner.query(`ALTER TABLE "session_allocation" ADD "sessionId" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "session_allocation" DROP COLUMN "userId"`);
        await queryRunner.query(`ALTER TABLE "session_allocation" ADD "userId" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "offer_preferences_session" DROP CONSTRAINT "FK_971f3356e937e94d7c26d27d15a"`);
        await queryRunner.query(`ALTER TABLE "offer" DROP CONSTRAINT "FK_0a9f568475b4a5401669c61333f"`);
        await queryRunner.query(`ALTER TABLE "offer" DROP CONSTRAINT "FK_e8100751be1076656606ae045e3"`);
        await queryRunner.query(`ALTER TABLE "offer" DROP CONSTRAINT "PK_57c6ae1abe49201919ef68de900"`);
        await queryRunner.query(`ALTER TABLE "offer" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "offer" ADD "id" uuid NOT NULL DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "offer" ADD CONSTRAINT "PK_57c6ae1abe49201919ef68de900" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "offer" DROP COLUMN "requestId"`);
        await queryRunner.query(`ALTER TABLE "offer" ADD "requestId" uuid`);
        await queryRunner.query(`ALTER TABLE "offer" DROP COLUMN "userId"`);
        await queryRunner.query(`ALTER TABLE "offer" ADD "userId" uuid`);
        await queryRunner.query(`ALTER TABLE "staff_request_swap_preference_session" DROP CONSTRAINT "FK_9159aa0df8131c1cd0f242c84dc"`);
        await queryRunner.query(`ALTER TABLE "staff_request" DROP CONSTRAINT "FK_f8d9da2b83b977dcc23b6c2fc60"`);
        await queryRunner.query(`ALTER TABLE "staff_request" DROP CONSTRAINT "FK_0f5d437fc98264cfb98dafdf080"`);
        await queryRunner.query(`ALTER TABLE "staff_request" DROP CONSTRAINT "FK_6e406f88ffcac36d89c6887d7be"`);
        await queryRunner.query(`ALTER TABLE "staff_request" DROP CONSTRAINT "FK_726c425ec6ac8e07a84332e6fbb"`);
        await queryRunner.query(`ALTER TABLE "staff_request" DROP CONSTRAINT "UQ_3aa706a41308e3fd7107bf5d078"`);
        await queryRunner.query(`ALTER TABLE "staff_request" DROP CONSTRAINT "PK_41bbafca9644c0f2bc09534df6d"`);
        await queryRunner.query(`ALTER TABLE "staff_request" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "staff_request" ADD "id" uuid NOT NULL DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "staff_request" ADD CONSTRAINT "PK_41bbafca9644c0f2bc09534df6d" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "staff_request" DROP COLUMN "requesterId"`);
        await queryRunner.query(`ALTER TABLE "staff_request" ADD "requesterId" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "staff_request" DROP COLUMN "sessionId"`);
        await queryRunner.query(`ALTER TABLE "staff_request" ADD "sessionId" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "staff_request" DROP COLUMN "acceptorId"`);
        await queryRunner.query(`ALTER TABLE "staff_request" ADD "acceptorId" uuid`);
        await queryRunner.query(`ALTER TABLE "staff_request" DROP COLUMN "finaliserId"`);
        await queryRunner.query(`ALTER TABLE "staff_request" ADD "finaliserId" uuid`);
        await queryRunner.query(`ALTER TABLE "staff_request_swap_preference_session" DROP CONSTRAINT "FK_c13a3a9d35ffb7497f0a93cb570"`);
        await queryRunner.query(`ALTER TABLE "offer_preferences_session" DROP CONSTRAINT "FK_3a098cb4f1707a4d217954cfab9"`);
        await queryRunner.query(`ALTER TABLE "session" DROP CONSTRAINT "FK_e18308596f3076e9de1d80c6f51"`);
        await queryRunner.query(`ALTER TABLE "session" DROP CONSTRAINT "UQ_3d57e44540eb64af0e24d4a02ab"`);
        await queryRunner.query(`ALTER TABLE "session" DROP CONSTRAINT "PK_f55da76ac1c3ac420f444d2ff11"`);
        await queryRunner.query(`ALTER TABLE "session" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "session" ADD "id" uuid NOT NULL DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "session" ADD CONSTRAINT "PK_f55da76ac1c3ac420f444d2ff11" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "session" DROP COLUMN "sessionStreamId"`);
        await queryRunner.query(`ALTER TABLE "session" ADD "sessionStreamId" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "stream_allocation" DROP CONSTRAINT "FK_b3d5528826d766b691e1132107f"`);
        await queryRunner.query(`ALTER TABLE "session_stream" DROP CONSTRAINT "FK_66028ae4744099f055d7763a503"`);
        await queryRunner.query(`ALTER TABLE "session_stream" DROP CONSTRAINT "PK_4c05a74aa4bcb6232e597f6be83"`);
        await queryRunner.query(`ALTER TABLE "session_stream" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "session_stream" ADD "id" uuid NOT NULL DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "session_stream" ADD CONSTRAINT "PK_4c05a74aa4bcb6232e597f6be83" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "session_stream" DROP COLUMN "timetableId"`);
        await queryRunner.query(`ALTER TABLE "session_stream" ADD "timetableId" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "stream_allocation" DROP CONSTRAINT "FK_bc7afec02062c5cedc6d14bd6af"`);
        await queryRunner.query(`ALTER TABLE "stream_allocation" DROP CONSTRAINT "UQ_8b449413d5d44c30ffff74aa0f0"`);
        await queryRunner.query(`ALTER TABLE "stream_allocation" DROP CONSTRAINT "PK_8ec85fd9f1f15f195b27a532dd9"`);
        await queryRunner.query(`ALTER TABLE "stream_allocation" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "stream_allocation" ADD "id" uuid NOT NULL DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "stream_allocation" ADD CONSTRAINT "PK_8ec85fd9f1f15f195b27a532dd9" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "stream_allocation" DROP COLUMN "sessionStreamId"`);
        await queryRunner.query(`ALTER TABLE "stream_allocation" ADD "sessionStreamId" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "stream_allocation" DROP COLUMN "userId"`);
        await queryRunner.query(`ALTER TABLE "stream_allocation" ADD "userId" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "timeslot" DROP CONSTRAINT "FK_47d06adf246fcfea1d318423ee3"`);
        await queryRunner.query(`ALTER TABLE "timeslot" DROP CONSTRAINT "PK_cd8bca557ee1eb5b090b9e63009"`);
        await queryRunner.query(`ALTER TABLE "timeslot" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "timeslot" ADD "id" uuid NOT NULL DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "timeslot" ADD CONSTRAINT "PK_cd8bca557ee1eb5b090b9e63009" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "timeslot" DROP COLUMN "userId"`);
        await queryRunner.query(`ALTER TABLE "timeslot" ADD "userId" uuid`);
        await queryRunner.query(`ALTER TABLE "course_staff" DROP CONSTRAINT "FK_2e099fcbb0ffe5108a4df4b31c8"`);
        await queryRunner.query(`ALTER TABLE "user" DROP CONSTRAINT "PK_cace4a159ff9f2512dd42373760"`);
        await queryRunner.query(`ALTER TABLE "user" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "user" ADD "id" uuid NOT NULL DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "user" ADD CONSTRAINT "PK_cace4a159ff9f2512dd42373760" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "course_staff" DROP CONSTRAINT "FK_d3dfdd3bab57eedfcf1e45bc72d"`);
        await queryRunner.query(`ALTER TABLE "preference" DROP CONSTRAINT "PK_5c4cbf49a1e97dcbc695bf462a6"`);
        await queryRunner.query(`ALTER TABLE "preference" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "preference" ADD "id" uuid NOT NULL DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "preference" ADD CONSTRAINT "PK_5c4cbf49a1e97dcbc695bf462a6" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "course_staff" DROP CONSTRAINT "FK_2f8044368c327e2ad804dc1fe56"`);
        await queryRunner.query(`ALTER TABLE "course_staff" DROP CONSTRAINT "UQ_f33c09ecdf4a0ee5a8a27ac971d"`);
        await queryRunner.query(`ALTER TABLE "course_staff" DROP CONSTRAINT "PK_6bc9388e2bf79cf6de4678dc81b"`);
        await queryRunner.query(`ALTER TABLE "course_staff" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "course_staff" ADD "id" uuid NOT NULL DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "course_staff" ADD CONSTRAINT "PK_6bc9388e2bf79cf6de4678dc81b" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "course_staff" DROP COLUMN "userId"`);
        await queryRunner.query(`ALTER TABLE "course_staff" ADD "userId" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "course_staff" DROP COLUMN "timetableId"`);
        await queryRunner.query(`ALTER TABLE "course_staff" ADD "timetableId" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "course_staff" DROP CONSTRAINT "REL_d3dfdd3bab57eedfcf1e45bc72"`);
        await queryRunner.query(`ALTER TABLE "course_staff" DROP COLUMN "preferenceId"`);
        await queryRunner.query(`ALTER TABLE "course_staff" ADD "preferenceId" uuid`);
        await queryRunner.query(`ALTER TABLE "course_staff" ADD CONSTRAINT "UQ_d3dfdd3bab57eedfcf1e45bc72d" UNIQUE ("preferenceId")`);
        await queryRunner.query(`ALTER TABLE "timetable" DROP CONSTRAINT "FK_9cc6b2c53c23571cad8390666f4"`);
        await queryRunner.query(`ALTER TABLE "timetable" DROP CONSTRAINT "UQ_091ca503e51c3de094972d48cb2"`);
        await queryRunner.query(`ALTER TABLE "timetable" DROP CONSTRAINT "PK_06001d91b3fe346fb1387ad1a15"`);
        await queryRunner.query(`ALTER TABLE "timetable" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "timetable" ADD "id" uuid NOT NULL DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "timetable" ADD CONSTRAINT "PK_06001d91b3fe346fb1387ad1a15" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "timetable" DROP COLUMN "courseId"`);
        await queryRunner.query(`ALTER TABLE "timetable" ADD "courseId" uuid`);
        await queryRunner.query(`ALTER TABLE "timetable" DROP COLUMN "termId"`);
        await queryRunner.query(`ALTER TABLE "timetable" ADD "termId" uuid`);
        await queryRunner.query(`ALTER TABLE "course" DROP CONSTRAINT "PK_bf95180dd756fd204fb01ce4916"`);
        await queryRunner.query(`ALTER TABLE "course" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "course" ADD "id" uuid NOT NULL DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "course" ADD CONSTRAINT "PK_bf95180dd756fd204fb01ce4916" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "offer_preferences_session" DROP CONSTRAINT "PK_192129d1763740f5519d150d033"`);
        await queryRunner.query(`ALTER TABLE "offer_preferences_session" ADD CONSTRAINT "PK_3a098cb4f1707a4d217954cfab9" PRIMARY KEY ("sessionId")`);
        await queryRunner.query(`DROP INDEX "IDX_971f3356e937e94d7c26d27d15"`);
        await queryRunner.query(`ALTER TABLE "offer_preferences_session" DROP COLUMN "offerId"`);
        await queryRunner.query(`ALTER TABLE "offer_preferences_session" ADD "offerId" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "offer_preferences_session" DROP CONSTRAINT "PK_3a098cb4f1707a4d217954cfab9"`);
        await queryRunner.query(`ALTER TABLE "offer_preferences_session" ADD CONSTRAINT "PK_192129d1763740f5519d150d033" PRIMARY KEY ("sessionId", "offerId")`);
        await queryRunner.query(`ALTER TABLE "offer_preferences_session" DROP CONSTRAINT "PK_192129d1763740f5519d150d033"`);
        await queryRunner.query(`ALTER TABLE "offer_preferences_session" ADD CONSTRAINT "PK_971f3356e937e94d7c26d27d15a" PRIMARY KEY ("offerId")`);
        await queryRunner.query(`DROP INDEX "IDX_3a098cb4f1707a4d217954cfab"`);
        await queryRunner.query(`ALTER TABLE "offer_preferences_session" DROP COLUMN "sessionId"`);
        await queryRunner.query(`ALTER TABLE "offer_preferences_session" ADD "sessionId" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "offer_preferences_session" DROP CONSTRAINT "PK_971f3356e937e94d7c26d27d15a"`);
        await queryRunner.query(`ALTER TABLE "offer_preferences_session" ADD CONSTRAINT "PK_192129d1763740f5519d150d033" PRIMARY KEY ("offerId", "sessionId")`);
        await queryRunner.query(`ALTER TABLE "staff_request_swap_preference_session" DROP CONSTRAINT "PK_8d7af521a17327e34412a71a699"`);
        await queryRunner.query(`ALTER TABLE "staff_request_swap_preference_session" ADD CONSTRAINT "PK_c13a3a9d35ffb7497f0a93cb570" PRIMARY KEY ("sessionId")`);
        await queryRunner.query(`DROP INDEX "IDX_9159aa0df8131c1cd0f242c84d"`);
        await queryRunner.query(`ALTER TABLE "staff_request_swap_preference_session" DROP COLUMN "staffRequestId"`);
        await queryRunner.query(`ALTER TABLE "staff_request_swap_preference_session" ADD "staffRequestId" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "staff_request_swap_preference_session" DROP CONSTRAINT "PK_c13a3a9d35ffb7497f0a93cb570"`);
        await queryRunner.query(`ALTER TABLE "staff_request_swap_preference_session" ADD CONSTRAINT "PK_8d7af521a17327e34412a71a699" PRIMARY KEY ("sessionId", "staffRequestId")`);
        await queryRunner.query(`ALTER TABLE "staff_request_swap_preference_session" DROP CONSTRAINT "PK_8d7af521a17327e34412a71a699"`);
        await queryRunner.query(`ALTER TABLE "staff_request_swap_preference_session" ADD CONSTRAINT "PK_9159aa0df8131c1cd0f242c84dc" PRIMARY KEY ("staffRequestId")`);
        await queryRunner.query(`DROP INDEX "IDX_c13a3a9d35ffb7497f0a93cb57"`);
        await queryRunner.query(`ALTER TABLE "staff_request_swap_preference_session" DROP COLUMN "sessionId"`);
        await queryRunner.query(`ALTER TABLE "staff_request_swap_preference_session" ADD "sessionId" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "staff_request_swap_preference_session" DROP CONSTRAINT "PK_9159aa0df8131c1cd0f242c84dc"`);
        await queryRunner.query(`ALTER TABLE "staff_request_swap_preference_session" ADD CONSTRAINT "PK_8d7af521a17327e34412a71a699" PRIMARY KEY ("staffRequestId", "sessionId")`);
        await queryRunner.query(`CREATE INDEX "IDX_971f3356e937e94d7c26d27d15" ON "offer_preferences_session" ("offerId") `);
        await queryRunner.query(`CREATE INDEX "IDX_3a098cb4f1707a4d217954cfab" ON "offer_preferences_session" ("sessionId") `);
        await queryRunner.query(`CREATE INDEX "IDX_9159aa0df8131c1cd0f242c84d" ON "staff_request_swap_preference_session" ("staffRequestId") `);
        await queryRunner.query(`CREATE INDEX "IDX_c13a3a9d35ffb7497f0a93cb57" ON "staff_request_swap_preference_session" ("sessionId") `);
        await queryRunner.query(`ALTER TABLE "session_allocation" ADD CONSTRAINT "UQ_48fa99dd8231087c41a285f606f" UNIQUE ("sessionId", "userId")`);
        await queryRunner.query(`ALTER TABLE "staff_request" ADD CONSTRAINT "UQ_3aa706a41308e3fd7107bf5d078" UNIQUE ("requesterId", "sessionId")`);
        await queryRunner.query(`ALTER TABLE "session" ADD CONSTRAINT "UQ_3d57e44540eb64af0e24d4a02ab" UNIQUE ("sessionStreamId", "week")`);
        await queryRunner.query(`ALTER TABLE "stream_allocation" ADD CONSTRAINT "UQ_8b449413d5d44c30ffff74aa0f0" UNIQUE ("sessionStreamId", "userId")`);
        await queryRunner.query(`ALTER TABLE "course_staff" ADD CONSTRAINT "UQ_f33c09ecdf4a0ee5a8a27ac971d" UNIQUE ("timetableId", "userId")`);
        await queryRunner.query(`ALTER TABLE "timetable" ADD CONSTRAINT "UQ_091ca503e51c3de094972d48cb2" UNIQUE ("courseId", "termId")`);
        await queryRunner.query(`ALTER TABLE "session_allocation" ADD CONSTRAINT "FK_4229fc0a3545c3afd0bfb0bb7e4" FOREIGN KEY ("sessionId") REFERENCES "session"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "session_allocation" ADD CONSTRAINT "FK_4ad45c42f963d66b7d38b6e9fe8" FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "offer" ADD CONSTRAINT "FK_0a9f568475b4a5401669c61333f" FOREIGN KEY ("requestId") REFERENCES "staff_request"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "offer" ADD CONSTRAINT "FK_e8100751be1076656606ae045e3" FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "staff_request" ADD CONSTRAINT "FK_f8d9da2b83b977dcc23b6c2fc60" FOREIGN KEY ("requesterId") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "staff_request" ADD CONSTRAINT "FK_6e406f88ffcac36d89c6887d7be" FOREIGN KEY ("acceptorId") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "staff_request" ADD CONSTRAINT "FK_726c425ec6ac8e07a84332e6fbb" FOREIGN KEY ("finaliserId") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "staff_request" ADD CONSTRAINT "FK_0f5d437fc98264cfb98dafdf080" FOREIGN KEY ("sessionId") REFERENCES "session"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "session" ADD CONSTRAINT "FK_e18308596f3076e9de1d80c6f51" FOREIGN KEY ("sessionStreamId") REFERENCES "session_stream"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "session_stream" ADD CONSTRAINT "FK_66028ae4744099f055d7763a503" FOREIGN KEY ("timetableId") REFERENCES "timetable"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "stream_allocation" ADD CONSTRAINT "FK_b3d5528826d766b691e1132107f" FOREIGN KEY ("sessionStreamId") REFERENCES "session_stream"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "stream_allocation" ADD CONSTRAINT "FK_bc7afec02062c5cedc6d14bd6af" FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "timeslot" ADD CONSTRAINT "FK_47d06adf246fcfea1d318423ee3" FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "course_staff" ADD CONSTRAINT "FK_2f8044368c327e2ad804dc1fe56" FOREIGN KEY ("timetableId") REFERENCES "timetable"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "course_staff" ADD CONSTRAINT "FK_2e099fcbb0ffe5108a4df4b31c8" FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "course_staff" ADD CONSTRAINT "FK_d3dfdd3bab57eedfcf1e45bc72d" FOREIGN KEY ("preferenceId") REFERENCES "preference"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "timetable" ADD CONSTRAINT "FK_9cc6b2c53c23571cad8390666f4" FOREIGN KEY ("courseId") REFERENCES "course"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "timetable" ADD CONSTRAINT "FK_531f53d06003b9e25ed9f2f0cd3" FOREIGN KEY ("termId") REFERENCES "term"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "offer_preferences_session" ADD CONSTRAINT "FK_971f3356e937e94d7c26d27d15a" FOREIGN KEY ("offerId") REFERENCES "offer"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "offer_preferences_session" ADD CONSTRAINT "FK_3a098cb4f1707a4d217954cfab9" FOREIGN KEY ("sessionId") REFERENCES "session"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "staff_request_swap_preference_session" ADD CONSTRAINT "FK_9159aa0df8131c1cd0f242c84dc" FOREIGN KEY ("staffRequestId") REFERENCES "staff_request"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "staff_request_swap_preference_session" ADD CONSTRAINT "FK_c13a3a9d35ffb7497f0a93cb570" FOREIGN KEY ("sessionId") REFERENCES "session"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "staff_request_swap_preference_session" DROP CONSTRAINT "FK_c13a3a9d35ffb7497f0a93cb570"`);
        await queryRunner.query(`ALTER TABLE "staff_request_swap_preference_session" DROP CONSTRAINT "FK_9159aa0df8131c1cd0f242c84dc"`);
        await queryRunner.query(`ALTER TABLE "offer_preferences_session" DROP CONSTRAINT "FK_3a098cb4f1707a4d217954cfab9"`);
        await queryRunner.query(`ALTER TABLE "offer_preferences_session" DROP CONSTRAINT "FK_971f3356e937e94d7c26d27d15a"`);
        await queryRunner.query(`ALTER TABLE "timetable" DROP CONSTRAINT "FK_531f53d06003b9e25ed9f2f0cd3"`);
        await queryRunner.query(`ALTER TABLE "timetable" DROP CONSTRAINT "FK_9cc6b2c53c23571cad8390666f4"`);
        await queryRunner.query(`ALTER TABLE "course_staff" DROP CONSTRAINT "FK_d3dfdd3bab57eedfcf1e45bc72d"`);
        await queryRunner.query(`ALTER TABLE "course_staff" DROP CONSTRAINT "FK_2e099fcbb0ffe5108a4df4b31c8"`);
        await queryRunner.query(`ALTER TABLE "course_staff" DROP CONSTRAINT "FK_2f8044368c327e2ad804dc1fe56"`);
        await queryRunner.query(`ALTER TABLE "timeslot" DROP CONSTRAINT "FK_47d06adf246fcfea1d318423ee3"`);
        await queryRunner.query(`ALTER TABLE "stream_allocation" DROP CONSTRAINT "FK_bc7afec02062c5cedc6d14bd6af"`);
        await queryRunner.query(`ALTER TABLE "stream_allocation" DROP CONSTRAINT "FK_b3d5528826d766b691e1132107f"`);
        await queryRunner.query(`ALTER TABLE "session_stream" DROP CONSTRAINT "FK_66028ae4744099f055d7763a503"`);
        await queryRunner.query(`ALTER TABLE "session" DROP CONSTRAINT "FK_e18308596f3076e9de1d80c6f51"`);
        await queryRunner.query(`ALTER TABLE "staff_request" DROP CONSTRAINT "FK_0f5d437fc98264cfb98dafdf080"`);
        await queryRunner.query(`ALTER TABLE "staff_request" DROP CONSTRAINT "FK_726c425ec6ac8e07a84332e6fbb"`);
        await queryRunner.query(`ALTER TABLE "staff_request" DROP CONSTRAINT "FK_6e406f88ffcac36d89c6887d7be"`);
        await queryRunner.query(`ALTER TABLE "staff_request" DROP CONSTRAINT "FK_f8d9da2b83b977dcc23b6c2fc60"`);
        await queryRunner.query(`ALTER TABLE "offer" DROP CONSTRAINT "FK_e8100751be1076656606ae045e3"`);
        await queryRunner.query(`ALTER TABLE "offer" DROP CONSTRAINT "FK_0a9f568475b4a5401669c61333f"`);
        await queryRunner.query(`ALTER TABLE "session_allocation" DROP CONSTRAINT "FK_4ad45c42f963d66b7d38b6e9fe8"`);
        await queryRunner.query(`ALTER TABLE "session_allocation" DROP CONSTRAINT "FK_4229fc0a3545c3afd0bfb0bb7e4"`);
        await queryRunner.query(`ALTER TABLE "timetable" DROP CONSTRAINT "UQ_091ca503e51c3de094972d48cb2"`);
        await queryRunner.query(`ALTER TABLE "course_staff" DROP CONSTRAINT "UQ_f33c09ecdf4a0ee5a8a27ac971d"`);
        await queryRunner.query(`ALTER TABLE "stream_allocation" DROP CONSTRAINT "UQ_8b449413d5d44c30ffff74aa0f0"`);
        await queryRunner.query(`ALTER TABLE "session" DROP CONSTRAINT "UQ_3d57e44540eb64af0e24d4a02ab"`);
        await queryRunner.query(`ALTER TABLE "staff_request" DROP CONSTRAINT "UQ_3aa706a41308e3fd7107bf5d078"`);
        await queryRunner.query(`ALTER TABLE "session_allocation" DROP CONSTRAINT "UQ_48fa99dd8231087c41a285f606f"`);
        await queryRunner.query(`DROP INDEX "IDX_c13a3a9d35ffb7497f0a93cb57"`);
        await queryRunner.query(`DROP INDEX "IDX_9159aa0df8131c1cd0f242c84d"`);
        await queryRunner.query(`DROP INDEX "IDX_3a098cb4f1707a4d217954cfab"`);
        await queryRunner.query(`DROP INDEX "IDX_971f3356e937e94d7c26d27d15"`);
        await queryRunner.query(`ALTER TABLE "staff_request_swap_preference_session" DROP CONSTRAINT "PK_8d7af521a17327e34412a71a699"`);
        await queryRunner.query(`ALTER TABLE "staff_request_swap_preference_session" ADD CONSTRAINT "PK_9159aa0df8131c1cd0f242c84dc" PRIMARY KEY ("staffRequestId")`);
        await queryRunner.query(`ALTER TABLE "staff_request_swap_preference_session" DROP COLUMN "sessionId"`);
        await queryRunner.query(`ALTER TABLE "staff_request_swap_preference_session" ADD "sessionId" integer NOT NULL`);
        await queryRunner.query(`CREATE INDEX "IDX_c13a3a9d35ffb7497f0a93cb57" ON "staff_request_swap_preference_session" ("sessionId") `);
        await queryRunner.query(`ALTER TABLE "staff_request_swap_preference_session" DROP CONSTRAINT "PK_9159aa0df8131c1cd0f242c84dc"`);
        await queryRunner.query(`ALTER TABLE "staff_request_swap_preference_session" ADD CONSTRAINT "PK_8d7af521a17327e34412a71a699" PRIMARY KEY ("sessionId", "staffRequestId")`);
        await queryRunner.query(`ALTER TABLE "staff_request_swap_preference_session" DROP CONSTRAINT "PK_8d7af521a17327e34412a71a699"`);
        await queryRunner.query(`ALTER TABLE "staff_request_swap_preference_session" ADD CONSTRAINT "PK_c13a3a9d35ffb7497f0a93cb570" PRIMARY KEY ("sessionId")`);
        await queryRunner.query(`ALTER TABLE "staff_request_swap_preference_session" DROP COLUMN "staffRequestId"`);
        await queryRunner.query(`ALTER TABLE "staff_request_swap_preference_session" ADD "staffRequestId" integer NOT NULL`);
        await queryRunner.query(`CREATE INDEX "IDX_9159aa0df8131c1cd0f242c84d" ON "staff_request_swap_preference_session" ("staffRequestId") `);
        await queryRunner.query(`ALTER TABLE "staff_request_swap_preference_session" DROP CONSTRAINT "PK_c13a3a9d35ffb7497f0a93cb570"`);
        await queryRunner.query(`ALTER TABLE "staff_request_swap_preference_session" ADD CONSTRAINT "PK_8d7af521a17327e34412a71a699" PRIMARY KEY ("staffRequestId", "sessionId")`);
        await queryRunner.query(`ALTER TABLE "offer_preferences_session" DROP CONSTRAINT "PK_192129d1763740f5519d150d033"`);
        await queryRunner.query(`ALTER TABLE "offer_preferences_session" ADD CONSTRAINT "PK_971f3356e937e94d7c26d27d15a" PRIMARY KEY ("offerId")`);
        await queryRunner.query(`ALTER TABLE "offer_preferences_session" DROP COLUMN "sessionId"`);
        await queryRunner.query(`ALTER TABLE "offer_preferences_session" ADD "sessionId" integer NOT NULL`);
        await queryRunner.query(`CREATE INDEX "IDX_3a098cb4f1707a4d217954cfab" ON "offer_preferences_session" ("sessionId") `);
        await queryRunner.query(`ALTER TABLE "offer_preferences_session" DROP CONSTRAINT "PK_971f3356e937e94d7c26d27d15a"`);
        await queryRunner.query(`ALTER TABLE "offer_preferences_session" ADD CONSTRAINT "PK_192129d1763740f5519d150d033" PRIMARY KEY ("sessionId", "offerId")`);
        await queryRunner.query(`ALTER TABLE "offer_preferences_session" DROP CONSTRAINT "PK_192129d1763740f5519d150d033"`);
        await queryRunner.query(`ALTER TABLE "offer_preferences_session" ADD CONSTRAINT "PK_3a098cb4f1707a4d217954cfab9" PRIMARY KEY ("sessionId")`);
        await queryRunner.query(`ALTER TABLE "offer_preferences_session" DROP COLUMN "offerId"`);
        await queryRunner.query(`ALTER TABLE "offer_preferences_session" ADD "offerId" integer NOT NULL`);
        await queryRunner.query(`CREATE INDEX "IDX_971f3356e937e94d7c26d27d15" ON "offer_preferences_session" ("offerId") `);
        await queryRunner.query(`ALTER TABLE "offer_preferences_session" DROP CONSTRAINT "PK_3a098cb4f1707a4d217954cfab9"`);
        await queryRunner.query(`ALTER TABLE "offer_preferences_session" ADD CONSTRAINT "PK_192129d1763740f5519d150d033" PRIMARY KEY ("offerId", "sessionId")`);
        await queryRunner.query(`ALTER TABLE "course" DROP CONSTRAINT "PK_bf95180dd756fd204fb01ce4916"`);
        await queryRunner.query(`ALTER TABLE "course" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "course" ADD "id" SERIAL NOT NULL`);
        await queryRunner.query(`ALTER TABLE "course" ADD CONSTRAINT "PK_bf95180dd756fd204fb01ce4916" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "timetable" DROP COLUMN "termId"`);
        await queryRunner.query(`ALTER TABLE "timetable" ADD "termId" integer`);
        await queryRunner.query(`ALTER TABLE "timetable" DROP COLUMN "courseId"`);
        await queryRunner.query(`ALTER TABLE "timetable" ADD "courseId" integer`);
        await queryRunner.query(`ALTER TABLE "timetable" DROP CONSTRAINT "PK_06001d91b3fe346fb1387ad1a15"`);
        await queryRunner.query(`ALTER TABLE "timetable" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "timetable" ADD "id" SERIAL NOT NULL`);
        await queryRunner.query(`ALTER TABLE "timetable" ADD CONSTRAINT "PK_06001d91b3fe346fb1387ad1a15" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "timetable" ADD CONSTRAINT "UQ_091ca503e51c3de094972d48cb2" UNIQUE ("courseId", "termId")`);
        await queryRunner.query(`ALTER TABLE "timetable" ADD CONSTRAINT "FK_9cc6b2c53c23571cad8390666f4" FOREIGN KEY ("courseId") REFERENCES "course"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "course_staff" DROP CONSTRAINT "UQ_d3dfdd3bab57eedfcf1e45bc72d"`);
        await queryRunner.query(`ALTER TABLE "course_staff" DROP COLUMN "preferenceId"`);
        await queryRunner.query(`ALTER TABLE "course_staff" ADD "preferenceId" integer`);
        await queryRunner.query(`ALTER TABLE "course_staff" ADD CONSTRAINT "REL_d3dfdd3bab57eedfcf1e45bc72" UNIQUE ("preferenceId")`);
        await queryRunner.query(`ALTER TABLE "course_staff" DROP COLUMN "timetableId"`);
        await queryRunner.query(`ALTER TABLE "course_staff" ADD "timetableId" integer NOT NULL`);
        await queryRunner.query(`ALTER TABLE "course_staff" DROP COLUMN "userId"`);
        await queryRunner.query(`ALTER TABLE "course_staff" ADD "userId" integer NOT NULL`);
        await queryRunner.query(`ALTER TABLE "course_staff" DROP CONSTRAINT "PK_6bc9388e2bf79cf6de4678dc81b"`);
        await queryRunner.query(`ALTER TABLE "course_staff" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "course_staff" ADD "id" SERIAL NOT NULL`);
        await queryRunner.query(`ALTER TABLE "course_staff" ADD CONSTRAINT "PK_6bc9388e2bf79cf6de4678dc81b" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "course_staff" ADD CONSTRAINT "UQ_f33c09ecdf4a0ee5a8a27ac971d" UNIQUE ("timetableId", "userId")`);
        await queryRunner.query(`ALTER TABLE "course_staff" ADD CONSTRAINT "FK_2f8044368c327e2ad804dc1fe56" FOREIGN KEY ("timetableId") REFERENCES "timetable"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "preference" DROP CONSTRAINT "PK_5c4cbf49a1e97dcbc695bf462a6"`);
        await queryRunner.query(`ALTER TABLE "preference" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "preference" ADD "id" SERIAL NOT NULL`);
        await queryRunner.query(`ALTER TABLE "preference" ADD CONSTRAINT "PK_5c4cbf49a1e97dcbc695bf462a6" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "course_staff" ADD CONSTRAINT "FK_d3dfdd3bab57eedfcf1e45bc72d" FOREIGN KEY ("preferenceId") REFERENCES "preference"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user" DROP CONSTRAINT "PK_cace4a159ff9f2512dd42373760"`);
        await queryRunner.query(`ALTER TABLE "user" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "user" ADD "id" SERIAL NOT NULL`);
        await queryRunner.query(`ALTER TABLE "user" ADD CONSTRAINT "PK_cace4a159ff9f2512dd42373760" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "course_staff" ADD CONSTRAINT "FK_2e099fcbb0ffe5108a4df4b31c8" FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "timeslot" DROP COLUMN "userId"`);
        await queryRunner.query(`ALTER TABLE "timeslot" ADD "userId" integer`);
        await queryRunner.query(`ALTER TABLE "timeslot" DROP CONSTRAINT "PK_cd8bca557ee1eb5b090b9e63009"`);
        await queryRunner.query(`ALTER TABLE "timeslot" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "timeslot" ADD "id" SERIAL NOT NULL`);
        await queryRunner.query(`ALTER TABLE "timeslot" ADD CONSTRAINT "PK_cd8bca557ee1eb5b090b9e63009" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "timeslot" ADD CONSTRAINT "FK_47d06adf246fcfea1d318423ee3" FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "stream_allocation" DROP COLUMN "userId"`);
        await queryRunner.query(`ALTER TABLE "stream_allocation" ADD "userId" integer NOT NULL`);
        await queryRunner.query(`ALTER TABLE "stream_allocation" DROP COLUMN "sessionStreamId"`);
        await queryRunner.query(`ALTER TABLE "stream_allocation" ADD "sessionStreamId" integer NOT NULL`);
        await queryRunner.query(`ALTER TABLE "stream_allocation" DROP CONSTRAINT "PK_8ec85fd9f1f15f195b27a532dd9"`);
        await queryRunner.query(`ALTER TABLE "stream_allocation" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "stream_allocation" ADD "id" SERIAL NOT NULL`);
        await queryRunner.query(`ALTER TABLE "stream_allocation" ADD CONSTRAINT "PK_8ec85fd9f1f15f195b27a532dd9" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "stream_allocation" ADD CONSTRAINT "UQ_8b449413d5d44c30ffff74aa0f0" UNIQUE ("sessionStreamId", "userId")`);
        await queryRunner.query(`ALTER TABLE "stream_allocation" ADD CONSTRAINT "FK_bc7afec02062c5cedc6d14bd6af" FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "session_stream" DROP COLUMN "timetableId"`);
        await queryRunner.query(`ALTER TABLE "session_stream" ADD "timetableId" integer NOT NULL`);
        await queryRunner.query(`ALTER TABLE "session_stream" DROP CONSTRAINT "PK_4c05a74aa4bcb6232e597f6be83"`);
        await queryRunner.query(`ALTER TABLE "session_stream" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "session_stream" ADD "id" SERIAL NOT NULL`);
        await queryRunner.query(`ALTER TABLE "session_stream" ADD CONSTRAINT "PK_4c05a74aa4bcb6232e597f6be83" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "session_stream" ADD CONSTRAINT "FK_66028ae4744099f055d7763a503" FOREIGN KEY ("timetableId") REFERENCES "timetable"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "stream_allocation" ADD CONSTRAINT "FK_b3d5528826d766b691e1132107f" FOREIGN KEY ("sessionStreamId") REFERENCES "session_stream"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "session" DROP COLUMN "sessionStreamId"`);
        await queryRunner.query(`ALTER TABLE "session" ADD "sessionStreamId" integer NOT NULL`);
        await queryRunner.query(`ALTER TABLE "session" DROP CONSTRAINT "PK_f55da76ac1c3ac420f444d2ff11"`);
        await queryRunner.query(`ALTER TABLE "session" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "session" ADD "id" SERIAL NOT NULL`);
        await queryRunner.query(`ALTER TABLE "session" ADD CONSTRAINT "PK_f55da76ac1c3ac420f444d2ff11" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "session" ADD CONSTRAINT "UQ_3d57e44540eb64af0e24d4a02ab" UNIQUE ("week", "sessionStreamId")`);
        await queryRunner.query(`ALTER TABLE "session" ADD CONSTRAINT "FK_e18308596f3076e9de1d80c6f51" FOREIGN KEY ("sessionStreamId") REFERENCES "session_stream"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "offer_preferences_session" ADD CONSTRAINT "FK_3a098cb4f1707a4d217954cfab9" FOREIGN KEY ("sessionId") REFERENCES "session"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "staff_request_swap_preference_session" ADD CONSTRAINT "FK_c13a3a9d35ffb7497f0a93cb570" FOREIGN KEY ("sessionId") REFERENCES "session"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "staff_request" DROP COLUMN "finaliserId"`);
        await queryRunner.query(`ALTER TABLE "staff_request" ADD "finaliserId" integer`);
        await queryRunner.query(`ALTER TABLE "staff_request" DROP COLUMN "acceptorId"`);
        await queryRunner.query(`ALTER TABLE "staff_request" ADD "acceptorId" integer`);
        await queryRunner.query(`ALTER TABLE "staff_request" DROP COLUMN "sessionId"`);
        await queryRunner.query(`ALTER TABLE "staff_request" ADD "sessionId" integer NOT NULL`);
        await queryRunner.query(`ALTER TABLE "staff_request" DROP COLUMN "requesterId"`);
        await queryRunner.query(`ALTER TABLE "staff_request" ADD "requesterId" integer`);
        await queryRunner.query(`ALTER TABLE "staff_request" DROP CONSTRAINT "PK_41bbafca9644c0f2bc09534df6d"`);
        await queryRunner.query(`ALTER TABLE "staff_request" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "staff_request" ADD "id" SERIAL NOT NULL`);
        await queryRunner.query(`ALTER TABLE "staff_request" ADD CONSTRAINT "PK_41bbafca9644c0f2bc09534df6d" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "staff_request" ADD CONSTRAINT "UQ_3aa706a41308e3fd7107bf5d078" UNIQUE ("sessionId", "requesterId")`);
        await queryRunner.query(`ALTER TABLE "staff_request" ADD CONSTRAINT "FK_726c425ec6ac8e07a84332e6fbb" FOREIGN KEY ("finaliserId") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "staff_request" ADD CONSTRAINT "FK_6e406f88ffcac36d89c6887d7be" FOREIGN KEY ("acceptorId") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "staff_request" ADD CONSTRAINT "FK_0f5d437fc98264cfb98dafdf080" FOREIGN KEY ("sessionId") REFERENCES "session"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "staff_request" ADD CONSTRAINT "FK_f8d9da2b83b977dcc23b6c2fc60" FOREIGN KEY ("requesterId") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "staff_request_swap_preference_session" ADD CONSTRAINT "FK_9159aa0df8131c1cd0f242c84dc" FOREIGN KEY ("staffRequestId") REFERENCES "staff_request"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "offer" DROP COLUMN "userId"`);
        await queryRunner.query(`ALTER TABLE "offer" ADD "userId" integer`);
        await queryRunner.query(`ALTER TABLE "offer" DROP COLUMN "requestId"`);
        await queryRunner.query(`ALTER TABLE "offer" ADD "requestId" integer`);
        await queryRunner.query(`ALTER TABLE "offer" DROP CONSTRAINT "PK_57c6ae1abe49201919ef68de900"`);
        await queryRunner.query(`ALTER TABLE "offer" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "offer" ADD "id" SERIAL NOT NULL`);
        await queryRunner.query(`ALTER TABLE "offer" ADD CONSTRAINT "PK_57c6ae1abe49201919ef68de900" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "offer" ADD CONSTRAINT "FK_e8100751be1076656606ae045e3" FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "offer" ADD CONSTRAINT "FK_0a9f568475b4a5401669c61333f" FOREIGN KEY ("requestId") REFERENCES "staff_request"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "offer_preferences_session" ADD CONSTRAINT "FK_971f3356e937e94d7c26d27d15a" FOREIGN KEY ("offerId") REFERENCES "offer"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "session_allocation" DROP COLUMN "userId"`);
        await queryRunner.query(`ALTER TABLE "session_allocation" ADD "userId" integer NOT NULL`);
        await queryRunner.query(`ALTER TABLE "session_allocation" DROP COLUMN "sessionId"`);
        await queryRunner.query(`ALTER TABLE "session_allocation" ADD "sessionId" integer NOT NULL`);
        await queryRunner.query(`ALTER TABLE "session_allocation" DROP CONSTRAINT "PK_52c1e1b8d5dfae4448fb5c0d122"`);
        await queryRunner.query(`ALTER TABLE "session_allocation" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "session_allocation" ADD "id" SERIAL NOT NULL`);
        await queryRunner.query(`ALTER TABLE "session_allocation" ADD CONSTRAINT "PK_52c1e1b8d5dfae4448fb5c0d122" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "session_allocation" ADD CONSTRAINT "UQ_48fa99dd8231087c41a285f606f" UNIQUE ("sessionId", "userId")`);
        await queryRunner.query(`ALTER TABLE "session_allocation" ADD CONSTRAINT "FK_4ad45c42f963d66b7d38b6e9fe8" FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "session_allocation" ADD CONSTRAINT "FK_4229fc0a3545c3afd0bfb0bb7e4" FOREIGN KEY ("sessionId") REFERENCES "session"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "term" ALTER COLUMN "weekNames" SET DEFAULT ARRAY[]`);
        await queryRunner.query(`COMMENT ON COLUMN "term"."weekNames" IS NULL`);
        await queryRunner.query(`ALTER TABLE "term" DROP CONSTRAINT "PK_55b0479f0743f2e5d5ec414821e"`);
        await queryRunner.query(`ALTER TABLE "term" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "term" ADD "id" SERIAL NOT NULL`);
        await queryRunner.query(`ALTER TABLE "term" ADD CONSTRAINT "PK_55b0479f0743f2e5d5ec414821e" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "timetable" ADD CONSTRAINT "FK_531f53d06003b9e25ed9f2f0cd3" FOREIGN KEY ("termId") REFERENCES "term"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

}
